[package]
name = "dialectica-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
ladybug = ["dialectica-graph/ladybug"]

[dependencies]
dialectica-capsule = { path = "../dialectica-capsule" }
dialectica-compiler = { path = "../dialectica-compiler" }
dialectica-extractor = { path = "../dialectica-extractor" }
dialectica-graph = { path = "../dialectica-graph" }
serde_json = "1"

[lints]
workspace = true
